apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ragflow-management-frontend.fullname" . }}-nginx
  labels:
    {{- include "ragflow-management-frontend.labels" . | nindent 4 }}
data:
  ragflow.conf.template: |
    {{- include "ragflow-management-frontend.nginxVhostConfig" . | nindent 4 }}