apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ragflow-management-backend.fullname" . }}
  labels:
    {{- include "ragflow-management-backend.labels" . | nindent 4 }}
automountServiceAccountToken: false