apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ragflow-task-executor.fullname" . }}
  labels:
    {{- include "ragflow-task-executor.labels" . | nindent 4 }}
automountServiceAccountToken: false
