"""
Regression tests for `api.utils.file_utils.validate_upload_mime`.

WHY THIS TEST EXISTS
--------------------
libmagic's mime database varies wildly across versions and OS distributions.
On a fresh dev box (or a stripped-down container) `magic.from_buffer` often
returns `application/octet-stream` for perfectly-valid Office files (docx,
xlsx, pptx, .zip) — even though the file carries the canonical PK\\x03\\x04
ZIP signature.

Without a fallback, every legitimate Office upload would be rejected with
"File content does not match its extension". Our validator therefore checks
the ZIP magic bytes when libmagic returns octet-stream for a zip-based
extension. These tests pin that fallback so an upstream merge or a
"simplification" of file_utils.py can't silently re-introduce the bug.

Discovered 2026-04-30 while extending the multitenant_http_api bridge —
upstream's test_file_type_validation[docx|excel|ppt] tests were red because
of this exact issue. Adding the fallback turned all three green AND fixed
a real production blocker for users on libmagic-trimmed boxes.

Run:
    uv run python -m pytest test/multitenant/test_upload_mime_validation.py -v
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "test" / "testcases"))

from api.utils.file_utils import validate_upload_mime  # noqa: E402


def _make_real_zip_blob() -> bytes:
    """Build a minimal but structurally-valid ZIP archive in memory."""
    import io
    import zipfile
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("[Content_Types].xml", b"<?xml version='1.0'?><Types/>")
    return buf.getvalue()


@pytest.mark.parametrize("ext", ["docx", "xlsx", "pptx", "zip"])
def test_real_zip_accepted_when_libmagic_says_octet_stream(monkeypatch, ext):
    """The fallback path: libmagic mis-identifies → zipfile.is_zipfile saves us.

    A future merge MUST NOT remove this fallback without failing this test.
    """
    import magic
    monkeypatch.setattr(
        magic, "from_buffer", lambda *a, **kw: "application/octet-stream"
    )
    err = validate_upload_mime(f"sample.{ext}", _make_real_zip_blob())
    assert err is None, (
        f"Valid ZIP file with .{ext} extension (libmagic→octet-stream) was "
        f"rejected: {err}. The zipfile.is_zipfile fallback in "
        "validate_upload_mime is gone — Office uploads will fail in prod."
    )


@pytest.mark.parametrize("ext", ["docx", "xlsx", "pptx", "zip"])
def test_random_octet_stream_still_rejected(monkeypatch, ext):
    """The security half: octet-stream WITHOUT real ZIP structure must fail.

    Even a binary that starts with PK\\x03\\x04 is rejected if it lacks a
    proper end-of-central-directory record — that's why we use
    zipfile.is_zipfile() (full structure) and not a 4-byte signature peek.
    """
    import magic
    monkeypatch.setattr(
        magic, "from_buffer", lambda *a, **kw: "application/octet-stream"
    )
    # PK signature + garbage — no central directory → not a real ZIP
    fake_zip_lookalike = b"PK\x03\x04" + b"\x00" * 64
    err = validate_upload_mime(f"trojan.{ext}", fake_zip_lookalike)
    assert err is not None, (
        f"Binary with fake PK signature but invalid ZIP structure was "
        f"accepted as .{ext} — the validator is too lax. An attacker "
        "could upload arbitrary data prefixed with PK\\x03\\x04."
    )
    assert "does not match its extension" in err

    # Plain ELF / no PK at all → also rejected (sanity)
    elf = b"\x7fELF\x02\x01\x01\x00" + b"\x00" * 32
    err2 = validate_upload_mime(f"trojan2.{ext}", elf)
    assert err2 is not None and "does not match its extension" in err2


@pytest.mark.parametrize("ext", ["docx", "xlsx", "pptx"])
def test_real_office_file_passes_end_to_end(ext):
    """Use the actual Office-file generators from upstream's test utils to
    exercise the validator end-to-end. If libmagic on this host returns the
    canonical Office mime, great — the primary path passes. If it returns
    octet-stream, the ZIP fallback must catch it.
    """
    from utils.file_utils import (  # type: ignore[import-not-found]
        create_docx_file,
        create_excel_file,
        create_ppt_file,
    )

    creators = {
        "docx": create_docx_file,
        "xlsx": create_excel_file,
        "pptx": create_ppt_file,
    }
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=f".{ext}", delete=False) as tmp:
        path = Path(tmp.name)
    creators[ext](path)
    blob = path.read_bytes()
    err = validate_upload_mime(path.name, blob)
    assert err is None, (
        f"Real {ext} file generated by upstream's create_{ext}_file fixture "
        f"was rejected with: {err}.  This breaks Office uploads on this host."
    )
